# Generated by Django 5.0 on 2023-12-31 07:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unitbidang', '0002_bidang_kodebidang_alter_unit_kodeunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AkunProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaAkun', models.CharField(max_length=100)),
                ('jenisInputOutput', models.CharField(choices=[('IN', 'Input'), ('OT', 'Output')], default='IN', max_length=2)),
                ('jenisProgram', models.CharField(choices=[('nonAsset', 'Non Asset'), ('yesAsset', 'Asset')], default='nonAsset', max_length=8)),
                ('kodeAkun', models.CharField(max_length=100)),
                ('creationDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('unitBidang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unitbidang.unit')),
            ],
        ),
    ]
