# Generated by Django 5.0 on 2024-01-01 01:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akunprogram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='akunprogram',
            name='anggaranRealisasi',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='akunprogram',
            name='anggaranSatuTahun',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='akunprogram',
            name='anggaranSelisih',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='akunprogram',
            name='anggaranTerencana',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='akunprogram',
            name='keterangan',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='akunprogram',
            name='kodeAnggaran',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='akunprogram',
            name='lastUpdateTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='akunprogram',
            name='periodeAnggaran',
            field=models.CharField(choices=[('bulan', 'Bulan'), ('tahun', 'Tahun')], default='bulan', max_length=5),
        ),
        migrations.AddField(
            model_name='akunprogram',
            name='sifatKreasi',
            field=models.CharField(choices=[('terencana', 'Terencana'), ('modifikasi', 'Modifikasi'), ('usulanbaru', 'Usulan Baru'), ('dipertimbangkan', 'Dipertimbangkan'), ('usulanditolak', 'Usulan Ditolak'), ('digugurkan', 'Digugurkan')], default='terencana', max_length=15),
        ),
        migrations.AddField(
            model_name='akunprogram',
            name='sifatPeriodeAnggaran',
            field=models.CharField(choices=[('fiks', 'Fiks'), ('fleksibel', 'Fleksibel')], default='fiks', max_length=9),
        ),
        migrations.AlterField(
            model_name='akunprogram',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='akunprogram',
            name='jenisInputOutput',
            field=models.CharField(choices=[('IN', 'Input'), ('OT', 'Output')], default='OT', max_length=2),
        ),
        migrations.CreateModel(
            name='AnggaranBulanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulanAnggaran', models.IntegerField(blank=True, null=True)),
                ('tahunAnggaran', models.IntegerField()),
                ('rupiahAnggaran', models.DecimalField(decimal_places=2, max_digits=25)),
                ('rupiahRealisasi', models.DecimalField(decimal_places=2, max_digits=25)),
                ('rupiahSelisih', models.DecimalField(decimal_places=2, max_digits=25)),
                ('statusProgram', models.CharField(blank=True, choices=[('sesuai', 'Sesuai'), ('melebihi', 'Melebihi'), ('kurangdari', 'Kurang Dari'), ('takterlaksanateknis', 'Tak Terlaksana Teknis'), ('takterlaksanadana', 'Tak Terlaksana Dana')], max_length=20, null=True)),
                ('keterangan', models.TextField()),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('lastUpdateTime', models.DateTimeField(auto_now=True)),
                ('jumlahRevisi', models.IntegerField(default=0)),
                ('revisiTerakhirOleh', models.CharField(default='admin', max_length=100)),
                ('akunProgram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akunprogram.akunprogram')),
            ],
        ),
    ]
