# Generated by Django 5.0 on 2023-12-31 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bidang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaBidang', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaUnit', models.CharField(max_length=200)),
                ('kodeUnit', models.CharField(max_length=200)),
                ('bidang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unitbidang.bidang')),
            ],
        ),
    ]
