# Generated by Django 5.0 on 2023-12-31 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitbidang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidang',
            name='kodeBidang',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='kodeUnit',
            field=models.CharField(max_length=10),
        ),
    ]
